<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
        <IsTrimmable>True</IsTrimmable>
        <IsAotCompatible>True</IsAotCompatible>
        <NoWarn>IDE0130</NoWarn>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)' == 'Release'">
        <Title>$(AssemblyName)</Title>
        <Version>2026.2.1</Version>
        <Authors>qian-o</Authors>
        <Copyright>MIT</Copyright>
        <PackageTags>slang;shader;dxc;shaderc</PackageTags>
        <Description>The .NET version of the Slang compiler, allowing the compilation of Slang code in a .NET environment.</Description>
        <RepositoryUrl>https://github.com/qian-o/Slangc.NET</RepositoryUrl>
        <PackageProjectUrl>https://github.com/qian-o/Slangc.NET</PackageProjectUrl>
        <PackageLicenseFile>LICENSE</PackageLicenseFile>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Roslynator.Analyzers" Version="4.15.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

</Project>
